### ISSUE TITLE
setup-api.py in tools/developer_tools/python-client doesn't build the api

### ISSUE THREAD

**Issue by jpqatanl** [AdvancedPhotonSource/ComponentDB#1600]
Should this file just be deleted?

**Comment by iTerminate** [comment]
Hi John, good observation! The setup_api.py file is not a valid name, python only accepts setup.py. I did however do this intentionally and during build I create a symlink to one of those files with the valid `setup.py` name. Here is a script where I do this also. 
https://github.com/AdvancedPhotonSource/ComponentDB/blob/master/sbin/cdb_release_cdb_api_pip.py
