### ISSUE TITLE
guides links

### ISSUE THREAD

**Issue by jeonghanlee** [AdvancedPhotonSource/ComponentDB#637]
Hi, I would like to get the developers and administrators guides. If possible, can anyone put them in the github site instead of APS internal site?

**Comment by iTerminate** [comment]
Hi @jeonghanlee I should probably pull the links off the page and see if there is any details I should document. The admin guide is now internal, it used to be public however it is a bit dated so it may be best for me to just update it. Do you have any specific question?

**Comment by jeonghanlee** [comment]
Hi @iTerminate, I don't have any specific question. I only need more documents about the componentDB. If you have any relevant documents (even if out-of-date) to be shared with me, it would be great for me to understand how the service be configured and works.

**Comment by iTerminate** [comment]
Thank you for your patience, I apologize for getting back so late, I missed the notification for your message. Are you talking about the python web service?

**Comment by jeonghanlee** [comment]
@iTerminate  I don't think I understand your question correctly. Right now, I would like to see administrators guide and developers guide documents.  

If you can share them with me through email or github link, it would be a great help for me to understand how ComponentDB could be configured  and could work.  Since without any documents on ComponentDB, I start to looking at every single files to track down what they are doing at each step.  

You will see many pull requests soon or later.

**Comment by iTerminate** [comment]
Yes, let me share those with you. Can you send me email at djarosz@anl.gov

**Comment by jeonghanlee** [comment]
I sent an email through my lab account. Thank you.

**Comment by jeonghanlee** [comment]
Thank you, I've got all.
