### ISSUE TITLE
SQL syntax error on `populate_settings_type.sql` file

### ISSUE THREAD

**Issue by jeonghanlee** [AdvancedPhotonSource/ComponentDB#658]
With the latest commit 424df13, I've got the following error message
```bash
You have an error in your SQL syntax; check the manual that corresponds to 
your MariaDB server version for the right syntax to use near 
'25046,'ItemDomainCableInventory.List.Display.Length','Display column for length ' at line 1
```

The main issue is `;` at the following 

https://github.com/AdvancedPhotonSource/ComponentDB/blob/424df13634bf017c3f314ecf5d1037707700e771/db/sql/static/populate_setting_type.sql#L496

After I changed it with `,`, the error message is gone.

**Comment by iTerminate** [comment]
What version of mariadb are you running?

**Comment by jeonghanlee** [comment]
The default version of Debian 10 I use. So the version is `10.3.22-MariaDB-0+deb10u1`.

**Comment by iTerminate** [comment]
I will need to update the sql scripts to be compatible with the new version however for now we are stuck with version 5.5. That is what comes with Redhat. I plan on updating the mysql version in the next release or the release after the next (3.10 or 3.11). 

The current recommendation I would have for you is to use docker to run the older version of mysql, its much easier than installing a nonsupported mysql version on your OS. 

Here are the instructions: https://github.com/AdvancedPhotonSource/ComponentDB/wiki/Setting-up-MariaDB-5.5.x-in-Docker

**Comment by jeonghanlee** [comment]
Good to know how to run Docker DB, I am looking for this. Thanks.

However, this issue isn't related with the version, I think, because `INSERT` statement doesn't have any `;` within the statement [1]. Maybe Redhat version simply ignores this without any warning or others.  

I will look at how the current sql files work with the latest (Debian's view) MariaDB. And since to create, and populate all sql files with modification is good with `10.3.22-MariaDB-0+deb10u1`, I will look at potential problems while I am configuring the ComponentDB one step by one step.  I will let you know what I could find them. 

[1] <https://docs.oracle.com/cd/E17952_01/mysql-5.5-en/insert.html>

**Comment by iTerminate** [comment]
Did you pull the latest? I think we had it wrong a couple of days ago

**Comment by jeonghanlee** [comment]
Yes, the latest one, before my pull request. Please see the file:

https://github.com/AdvancedPhotonSource/ComponentDB/blob/3dcabf3cdc367d3491f3010a153d770d554d01e5/db/sql/static/populate_setting_type.sql#L496

**Comment by jeonghanlee** [comment]
@iTerminate  Thank you for taking care about this.
